version: "3.7"

services:
  backend:
    build: backend
    command: yarn dev
    container_name: choreScheduler-backend
    environment:
      BACKEND_PORT: $BACKEND_PORT
    env_file:
      - .development.env
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - backend-deps:/usr/src/app/node_modules
      - ./prettier.config.js:/usr/src/prettier.config.js
      - ./.eslintrc.js:/usr/src/.eslintrc.js
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
      - 9229:9229
    networks:
      - choreScheduler
  frontend:
    build: frontend
    command: yarn dev
    container_name: choreScheduler-frontend
    environment:
      - FRONTEND_PORT=$FRONTEND_PORT
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .development.env
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - frontend-deps:/usr/src/app/node_modules
      - ./prettier.config.js:/usr/src/prettier.config.js
      - ./.eslintrc.js:/usr/src/.eslintrc.js
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - choreScheduler
  database:
    image: postgres:15.0-alpine3.16
    restart: always
    container_name: choreScheduler-database
    environment:
      DATABASE_PORT: $DATABASE_PORT
    env_file:
      - .development.env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - choreScheduler

volumes:
  frontend-deps:
  backend-deps:
  
networks:
  choreScheduler:
